version: '3.8'

services:
  zedex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2654:2654"
    volumes:
      - zedex-cache:/app/.zedex-cache
    environment:
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  zedex-cache: 